### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by songshengli-123** [lilygeorgescu/AED-SSMTL#12]
Hi, thank you for your interesting work!
May I ask how long did you train on the three datasets(ped2, shanghaitech, avenue )?
I train ped2 about 36h, is that normal?
How to speed up?

**Comment by lilygeorgescu** [comment]
Hi,

Thank you for your interest in our work!

The training time depends only on the GPU card that you are using. On RTX3090 takes up to 5h to train ped2, and almost 2 days to train ShanghaiTech (only for 3-4 epochs due to the size of the data set). 

Unfortunately, I cannot help you with speeding up the training time. The only optimization that can be done is to re-write the samples-reading function on another thread but I do not think that this is going to speed up too much because most of the processing time is spent on the forward pass.

Best,
Lili

**Comment by songshengli-123** [comment]
HI, I am confused about my train. I have trained ped2 on cpu about 30h, when I used GPU(NVIDIA A40, ubuntu20.04), it will make an error :
First,the program will stop long time at 
2022-12-06 15:22:59.157658: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2022-12-06 15:24:07.994298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
and then it makes an error 
2022-12-06 15:37:30.507759: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55fd327205c0,impl=0x55fd3271e5c0] did not memset GPU location; source: 0x7f7118ff6ca0; size: 8388608; pattern: ffffffff
2022-12-06 15:37:30.507772: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55fd327205c0,impl=0x55fd3271e5c0] did not memset GPU location; source: 0x7f7118ff6cc0; size: 8388608; pattern: ffffffff
2022-12-06 15:37:30.507794: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "/home/m22_songshengli/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/m22_songshengli/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/m22_songshengli/.conda/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata) ....
could you have this problem? how to solve it?
my env is: ubuntu20.04 GPUA40 tf1.14 cuda10.0, cudnn7.6. what about your version about cuda and cudnn?

**Comment by lilygeorgescu** [comment]
Hi,

It looks that there is a mismatch between the cuda version and tensorflow version, I do not know how to solve it. Did you try to only import tensorflow and see what happens or to create a session? 

My environment is ubuntu 20.04; gpu 3090 rtx; cuda 11.4; tensorflow 1.15.4.

Sorry for not helping you more,
Best,
Lili

**Comment by songshengli-123** [comment]
when I try to only import tensroflow and create a session on cuda10.0 and cuda7.6,
it worked on another program using gpu,such as a malmatirx, but it will make a mistake  when train ped2. 
when you use cuda 11.4,how did you solve this problem below?
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-11.4/lib64/usr/local/cuda-11.4/lib64:/usr/local/cuda-11.4/lib64

**Comment by lilygeorgescu** [comment]
Hi,

Sorry, I do not remember all the details, I created the environment two years ago following this post: https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/

Best,
Lili
